# Generated by Django 4.0.3 on 2022-04-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_device_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-created_at']},
        ),
    ]
